const $ = s => document.querySelector(s);
const esc = s => String(s ?? '').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const params = new URLSearchParams(location.search);
if(pageAliases[params.get('page')])params.set('page',pageAliases[params.get('page')]);
const parentView = params.get('view') === 'parent';
const embedded = params.get('embed') === '1';
const href = id => `?page=${encodeURIComponent(id)}&embed=1${parentView?'&view=parent':''}${params.get('notes')==='1'?'&notes=1':''}`;
const link = (id,label,cls='text-link') => `<a class="${cls}" href="${href(id)}">${esc(label || pages[id]?.title || id)} <span aria-hidden="true">↗</span></a>`;
function media(label,small=false){if(parentView)return `<div class="media ${small?'small':''}" role="img" aria-label="School photograph pending"><span>SDKS Sri Sri Academy</span><small>Photography coming soon</small></div>`;return `<div class="media ${small?'small':''}" role="img" aria-label="Placeholder: ${esc(label)}"><svg aria-hidden="true" viewBox="0 0 64 48"><rect x="1" y="1" width="62" height="46" rx="2"/><circle cx="43" cy="14" r="5"/><path d="M2 39L20 20L34 34L43 25L62 44"/></svg><span>${esc(label)}</span><small>IMAGE PLACEHOLDER</small></div>`}
function note(text){return text?`<aside class="source-note">${esc(text)}</aside>`:''}
function renderSection(s,i){
 const head=`<div class="section-heading"><span class="section-number">${String(i+2).padStart(2,'0')}</span><h2>${esc(s.title)}</h2></div>`;
 const body=esc(s.text || ''); let content='';
 if(s.type==='split') content=`<div class="split ${s.reverse?'reverse':''}"><div>${head}<p>${body}</p>${s.link?link(s.link,s.label):''}</div>${media(s.image)}</div>`;
 else if(s.type==='cards') content=`${head}<div class="cards count-${s.items.length}">${s.items.map(([t,d,l,label])=>`<article><h3>${esc(t)}</h3><p>${esc(d)}</p>${l?link(l,label||'About '+t):''}</article>`).join('')}</div>`;
 else if(s.type==='pillars') content=`<h2 class="sr-only">${esc(s.title)}</h2><div class="pillars">${s.items.map(([t,d,l])=>`<article><h3>${link(l,t)}</h3><p>${esc(d)}</p></article>`).join('')}</div>`;
 else if(s.type==='feature') content=`<div class="feature-layout"><div>${head}<p>${body}</p>${s.link?link(s.link,s.label,'button'):''}</div>${media(s.image)}</div>`;
 else if(s.type==='stories') content=`<div class="stories-layout"><div>${head}<p>${body}</p>${link('school-life',s.label||'See school life')}</div><div class="story-images">${s.items.map(([t,d,l])=>`<article>${media(t,true)}<h3>${link(l,t)}</h3><p>${esc(d)}</p></article>`).join('')}</div></div>`;
 else if(s.type==='prose') content=`<div class="prose">${head}<p>${body}</p></div>`;
 else if(s.type==='notice') content=`<div class="notice"><strong>${esc(s.title)}</strong><p>${body}</p></div>`;
 else if(s.type==='cta') content=`<div class="cta"><div><h2>${esc(s.title)}</h2>${body?`<p>${body}</p>`:''}</div><div class="actions">${link(s.link,s.label,'button')}${s.secondary?link(s.secondary,s.secondaryLabel):''}</div></div>`;
 else if(s.type==='steps') content=`${head}<ol class="steps">${s.items.map(([t,d],j)=>`<li><span>${j+1}</span><h3>${esc(t)}</h3><p>${esc(d)}</p></li>`).join('')}</ol>`;
 else if(s.type==='list') content=`${head}<div class="rows">${s.items.map(([t,d])=>`<article><h3>${esc(t)}</h3><p>${esc(d)}</p></article>`).join('')}</div>`;
 else if(s.type==='faq') content=`${head}<div class="faq">${s.items.map(([t,d])=>`<details><summary>${esc(t)}</summary><p>${esc(d)}</p></details>`).join('')}</div>`;
 else if(s.type==='docs') content=`${head}<ul class="docs">${s.items.map(t=>`<li><span class="file-mark" aria-hidden="true">PDF</span><span>${esc(t)}</span><span class="pending">File to be supplied</span></li>`).join('')}</ul>`;
 else if(s.type==='table') content=`${head}<div class="table-wrap" tabindex="0" role="region" aria-label="${esc(s.title)}"><table><thead><tr>${s.headers.map(t=>`<th scope="col">${esc(t)}</th>`).join('')}</tr></thead><tbody>${s.rows.map(row=>`<tr>${row.map((t,k)=>`<${k?'td':'th scope="row"'}>${esc(t)}</${k?'td':'th'}>`).join('')}</tr>`).join('')}</tbody></table></div>`;
 else if(s.type==='gallery') content=`${head}<div class="gallery">${s.items.map((t,j)=>`<figure>${media(t,true)}<figcaption>${String(j+1).padStart(2,'0')} / ${esc(t)}<small>Caption, date and image status</small></figcaption></figure>`).join('')}</div>`;
 else if(s.type==='contact') content=`${head}<div class="split"><div class="contact-details"><h3>SDKS Sri Sri Academy</h3><p>Patiala, Punjab</p><dl><dt>Campus address</dt><dd>[Confirmed visitor address]</dd><dt>Phone & email</dt><dd>[Official contact details]</dd><dt>Office hours</dt><dd>[Confirmed hours]</dd><dt>Admission counsellor</dt><dd>[Official enquiry contact]</dd></dl></div>${media('Map / confirmed campus location')}</div>`;
 else if(s.type==='form') content=`${head}<div class="form-layout"><div><h3>Speak with the school</h3><p>This form demonstrates the enquiry layout. Please use sample information only.</p><p class="muted">Nothing is stored or sent.</p></div><form><label>Parent / guardian name<input name="parent" required autocomplete="off" placeholder="Sample name"></label><label>Email<input name="email" type="email" required autocomplete="off" placeholder="parent@example.com"></label><label>Class of interest<select name="class" required><option value="">Select a class</option>${['Nursery','Kindergarten — class to confirm','Class I','Class II','Class III','Class IV','Class V'].map(c=>`<option>${esc(c)}</option>`).join('')}</select></label><label>Message <span class="muted">(optional)</span><textarea name="message" rows="3" placeholder="Your question"></textarea></label><p class="fine">Read the ${link('privacy','privacy information')}.</p><button type="submit" class="button">Preview enquiry</button><p class="form-result" role="status" aria-live="polite"></p></form></div>`;
 return `<section class="block block-${s.type}" id="section-${i+2}"><div class="container">${content}${note(s.note)}</div></section>`;
}
function website(id){
 const p=pages[id]; if(!p){location.replace(href('home'));return;}
 document.title=`${p.title} · SDKS wireframe`;
 document.body.className=`website ${parentView?'parent-view':''} ${params.get('notes')==='1'?'show-notes':''}`;
 const nav=schoolNavigation.map(([id,label])=>link(id,label,'nav-link')).join('')+link('admissions','Apply Now','button nav-apply');
  $('#app').innerHTML=`<a href="#main" class="skip">Skip to content</a><div class="prototype-strip">WEBSITE WIREFRAME <span>Structure review · Not the live school website</span></div><header class="site-header"><div class="header-inner"><a class="brand" href="${href('home')}"><span class="logo-box">LOGO</span><span>SDKS Sri Sri Academy<small>Patiala</small></span></a><button class="menu-button" aria-expanded="false" aria-controls="site-nav">Menu <span aria-hidden="true">☰</span></button><nav id="site-nav" aria-label="Main navigation">${nav}</nav></div></header><main id="main" tabindex="-1">${id!=='home'?`<div class="container breadcrumb">${link('home','Home')}${false?`<span>/</span>${link('learning','Pedagogy')}`:''}${false?`<span>/</span>${link('campus','Infrastructure')}`:''}<span>/</span><span aria-current="page">${esc(p.title)}</span></div>`:''}<section class="hero ${p.image?'':'text-hero'}"><div class="container ${p.image?'split':''}"><div><p class="eyebrow">${id==='home'?'SDKS Sri Sri Academy · Patiala':esc(p.title)}</p><h1>${esc(p.intro)}</h1><p class="lead">${esc(p.desc)}</p>${id==='home'?link('about','Explore the school','button'):''}</div>${p.image?media(p.image):''}</div><div class="container">${note(p.note)}</div></section>${p.sections.map(renderSection).join('')}</main><footer><div class="container footer-grid"><div><strong>SDKS Sri Sri Academy</strong><p>Patiala, Punjab</p><small>Website structure for review.<br>Final content and images to be approved.</small></div><div><h2>Explore</h2>${['about','learning','campus','sports','activities','school-life'].map(k=>link(k)).join('')}</div><div><h2>Information</h2>${['admissions','contact','careers'].map(k=>link(k)).join('')}</div><div><h2>School documents</h2>${link('disclosure')}${link('privacy')}<p class="fine">Official social links will appear here.</p></div></div></footer>`;
 if(p.group==='About'&&id!=='about')$('.breadcrumb').children[1].insertAdjacentHTML('afterend',`${link('about','About')}<span>/</span>`);
 document.querySelectorAll('main p,main dd,main td').forEach(el=>{const value=el.textContent.trim();if(/^\[[\s\S]+\]$/.test(value)){el.innerHTML=`<span class="missing-label">School input needed</span><span class="source-note">${esc(value.slice(1,-1))}</span>`;}});
 if(id==='home'){const a=$('.hero .button');a.href=href('contact');a.innerHTML='Enquire now <span aria-hidden="true">↗</span>';document.body.classList.add('homepage');}
 $('.menu-button').onclick=()=>{const b=$('.menu-button'),open=b.getAttribute('aria-expanded')!=='true';b.setAttribute('aria-expanded',String(open));$('#site-nav').classList.toggle('open',open);};
 document.addEventListener('keydown',e=>{if(e.key==='Escape'){document.querySelectorAll('details[open]').forEach(d=>d.open=false);$('.menu-button').setAttribute('aria-expanded','false');$('#site-nav').classList.remove('open');}});
 document.querySelectorAll('.nav-group').forEach(d=>d.addEventListener('toggle',()=>{if(d.open)document.querySelectorAll('.nav-group').forEach(other=>{if(other!==d)other.open=false;});}));
 document.querySelectorAll('form').forEach(form=>form.addEventListener('submit',e=>{e.preventDefault();form.querySelector('.form-result').textContent='Preview complete. No enquiry was sent and no information was saved.';form.reset();}));
 document.querySelectorAll('a').forEach(a=>{if(a.href.includes('?page='))a.addEventListener('click',e=>{if(window.parent!==window){e.preventDefault();window.parent.postMessage({type:'sdks-navigate',page:new URL(a.href).searchParams.get('page')},location.origin);}});});
}
function review(){
 document.body.className='review';
 let active=pages[params.get('page')]?params.get('page'):'home';
 let device=['desktop','tablet','mobile'].includes(params.get('device'))?params.get('device'):'desktop';
 let notes=params.get('notes')==='1';
 let userView=parentView;
 $('#app').innerHTML=`<header class="review-bar"><a class="review-brand" href="?page=home">SDKS<span>Website structure</span></a><div class="device-controls" role="group" aria-label="Preview size"><button data-device="desktop">Desktop</button><button data-device="tablet">Tablet</button><button data-device="mobile">Mobile</button></div><div class="review-actions"><button id="view-toggle" aria-pressed="false">Parent view</button><button id="note-toggle" aria-pressed="false">Source notes</button><button id="map-toggle" aria-expanded="false" aria-controls="sitemap">All pages</button></div></header><div class="review-subbar"><label for="page-select">PAGE</label><select id="page-select">${Object.entries(pages).map(([k,p])=>`<option value="${k}">${esc(p.title)}</option>`).join('')}</select><span id="page-count"></span><a id="direct-link" target="_blank" rel="noopener">Open page ↗</a></div><section id="sitemap" class="sitemap" hidden><div class="map-head"><div><h1>Website page structure</h1><p>Select any page to explore its layout. Page count remains open for review.</p></div><button id="map-close" aria-label="Close page structure">Close ×</button></div><div class="map-grid">${['Start','About','Learning','Campus','Practical','School'].map(g=>`<div><h2>${g}</h2>${Object.entries(pages).filter(([,p])=>p.group===g).map(([k,p])=>`<button data-page="${k}">${esc(p.title)} ↗</button>`).join('')}</div>`).join('')}</div></section><main class="preview-stage"><div id="device-frame"><iframe title="School website wireframe preview" id="preview"></iframe></div></main><footer class="review-bottom"><span>Grayscale layout · Placeholder images · Demo forms</span><span id="viewport-label"></span></footer>`;
 $('.review-actions').insertAdjacentHTML('beforeend','<a class="inputs-link" href="school-inputs.html" target="_blank" rel="noopener">School inputs ↗</a>');
 const update=()=>{const query=new URLSearchParams({page:active,device,...(userView?{view:'parent'}:{}),...(notes?{notes:'1'}:{})});history.replaceState(null,'','?'+query);$('#page-select').value=active;$('#page-count').textContent=`${Object.keys(pages).indexOf(active)+1} / ${Object.keys(pages).length}`;$('#device-frame').className=device;$('#preview').src=`?page=${active}&embed=1${userView?'&view=parent':''}${notes?'&notes=1':''}`;$('#direct-link').href=`?page=${active}&embed=1${userView?'&view=parent':''}${notes?'&notes=1':''}`;$('#view-toggle').setAttribute('aria-pressed',String(userView));$('#view-toggle').textContent=userView?'Back to review':'Parent view';document.body.classList.toggle('parent-preview',userView);$('#note-toggle').disabled=userView;$('#note-toggle').setAttribute('aria-pressed',String(notes));document.querySelectorAll('[data-device]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.device===device)));$('#viewport-label').textContent=device==='mobile'?'Mobile · 390 px':device==='tablet'?'Tablet · 768 px':'Desktop · responsive';document.title=`${pages[active].title} · SDKS website review`;};
 const closeMap=()=>{$('#sitemap').hidden=true;$('#map-toggle').setAttribute('aria-expanded','false');};
 $('#page-select').onchange=e=>{active=e.target.value;update();};
 document.querySelectorAll('[data-device]').forEach(b=>b.onclick=()=>{device=b.dataset.device;update();});
 $('#view-toggle').onclick=()=>{userView=!userView;update();};
 $('#note-toggle').onclick=()=>{notes=!notes;update();};
 $('#map-toggle').onclick=()=>{const open=$('#sitemap').hidden;$('#sitemap').hidden=!open;$('#map-toggle').setAttribute('aria-expanded',String(open));};$('#map-close').onclick=closeMap;
 document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>{active=b.dataset.page;closeMap();update();});
 window.addEventListener('message',e=>{if(e.origin===location.origin&&e.source===$('#preview').contentWindow&&e.data?.type==='sdks-navigate'&&pages[e.data.page]){active=e.data.page;update();}});
 window.addEventListener('keydown',e=>{if(e.key==='Escape')closeMap();});update();
}
embedded?website(params.get('page') || 'home'):review();
