/* Website review content only. No personal records or source attachments. */
const pages = {
 home:{title:'Home',group:'Start',intro:'The Art of Living.\nThe Joy of Learning.',desc:'At SDKS Sri Sri Academy, Patiala, our approach combines contemporary education with timeless values, experiential learning and holistic development.',image:'Children and campus / hero photograph',note:'Headline selected by the school, as reported by the user, from image 2. Body arrangement follows image 1. Intro adapted from principal: About. This selection does not approve sample image facts, dates, logos or quotations.',sections:[
 {type:'pillars',title:'Our approach',items:[['Academic learning','Language, numeracy and inquiry.','learning'],['Holistic development','Learning across mind, body and emotions.','learning'],['Values & character','Compassion, cooperation and responsibility.','about'],['Belonging','A sense of connection with others.','school-life']],note:'Compact strip following image 1. Labels grounded in principal About/Vision/Pedagogy. Global perspective is omitted because a specific school programme has not been supplied.'},
 {type:'split',title:'A Space for Bigger Dreams',text:'Our campus in Patiala is under development. Plans include smart classrooms, a multipurpose hall, activity rooms and a wellness and yoga centre.',image:'Campus overview / clearly labelled architectural render',link:'campus',label:'Explore the campus',note:'Image 1 placement and heading. Discovery confirms construction; principal names these four facilities. Current progress and readiness need an update. No acreage or completion percentage imported.'},
 {type:'feature',title:'Learning to care for others',text:'We see education as a way of serving society. Our aim is to nurture responsible, compassionate individuals in an environment where cooperation and belonging can flourish.',image:'Values / child and nature image',link:'about',label:'Our vision and mission',note:'Full-width values feature from image 1, with copy adapted from principal: About. Misattributed reference quotation excluded.'},
 {type:'stories',title:'Learning Goes Beyond Classrooms',text:'The school’s plans include cultural activities, sport, meditation and life skills alongside classroom learning.',items:[['Arts & culture','Cultural activities and festivals.','school-life'],['Sports & wellbeing','Athletics, games and movement.','sports'],['Meditation & values','Assemblies, yoga and meditation.','school-life'],['Life skills & belonging','Learning to participate and cooperate.','school-life']],note:'Image 1 visual row. Principal: Sports, Activities and Life @SDKS-SSA. Community service is not presented as an established programme; examples and images remain required.'},
 {type:'feature',title:'Be a Part of Their Journey',text:'Learn about the school’s approach for Nursery–Class V, or contact us with your questions.',image:'Children / closing invitation image',link:'contact',label:'Enquire now',note:'Closing visual placement and heading follow image 1. This opens a demo enquiry, not an admission application.'}]},
 about:{title:'About the School',group:'About',intro:'About SDKS Sri Sri Academy',desc:'SDKS Sri Sri Academy brings together the values of Sanatan Dharma Kumar Sabha and the educational philosophy inspired by Gurudev Sri Sri Ravi Shankar.',image:'School / institutional photograph',note:'Principal: About. School-provided wording, edited for readability. Confirm exact institutional/legal association wording before final publication.',sections:[
 {type:'prose',title:'Our approach to education',text:'We see education as a means of serving society by nurturing responsible, compassionate and value-driven individuals. Our approach combines contemporary education with timeless values and experiential learning. We aim to create an environment where compassion, cooperation, joy and belonging flourish naturally.',note:'Principal: About, paraphrased without adding new claims. Origin dates/history not supplied and not invented.'},
 {type:'cards',title:'Our vision and mission',items:[['Vision','To nurture confident, compassionate and capable individuals through holistic, value-based education.'],['Mission','Child-centred, experiential and joyful learning that respects each learner’s individuality and pace.']],note:'Condensed from the principal’s Vision and Mission; no invented quotation.'},
 {type:'cards',title:'Messages from the school leadership',items:[["Chairman’s Message",'Read the chairman’s message.','chairman-message'],["Principal’s Message",'Read the principal’s message.','principal-message']],note:'Separate message pages requested by the user. Names, portraits and personal messages must be supplied and approved by the school.'},
 {type:'cta',title:'Our teaching approach',link:'learning',label:'Explore learning'}]},
 'chairman-message':{title:'Chairman’s Message',group:'About',intro:'A message from the chairman',desc:'[Chairman’s name and official designation.]',image:'Chairman portrait',note:'User-requested separate page. No name, portrait or personal statement supplied yet.',sections:[{type:'prose',title:'Chairman’s Message',text:'[School-approved message from the chairman, approximately 150–200 words, on the purpose behind the school and its long-term vision.]',note:'Preserve the chairman’s own voice. Edit only with approval; do not invent a personal statement.'},{type:'cta',title:'More about the school',link:'about',label:'About SDKS',secondary:'principal-message',secondaryLabel:'Principal’s Message'}]},
 'principal-message':{title:'Principal’s Message',group:'About',intro:'A message from the principal',desc:'[Principal’s name and official designation.]',image:'Principal portrait',note:'Separate page requested by the user; discovery also requests principal profile and message.',sections:[{type:'prose',title:'Principal’s Message',text:'[School-approved message from the principal, approximately 150–200 words, on teaching, children’s development and working with families.]',note:'The principal’s website draft is not a signed personal message. Request the actual message and approved portrait.'},{type:'cta',title:'Explore the school',link:'learning',label:'Our teaching approach',secondary:'chairman-message',secondaryLabel:'Chairman’s Message'}]},
 learning:{title:'Learning',group:'Learning',intro:'How children will learn',desc:'Our approach is child-centred, experiential and joyful. It respects each learner’s individuality and pace.',image:'Learning / teacher interaction image',note:'Principal: Mission and Pedagogy. Edited school copy, not a claim that classes have started.',sections:[
 {type:'cards',title:'Choose a learning stage',items:[['Nursery–Class II','A play-based foundation in language, numbers, creativity and social skills.','early-years'],['Classes III–V','An inquiry-based approach to subjects, ideas and everyday understanding.','primary']],note:'Principal stages; discovery confirms Year 1 Nursery–Class V.'},
 {type:'split',title:'Learning through experience',text:'In the foundational years, learning is play-based, with a focus on early literacy, numeracy, creativity and social-emotional skills. In Classes III–V, the approach becomes inquiry-based, with greater emphasis on subjects, creativity and critical thinking.',image:'Hands-on activity / learning materials',note:'Principal: Pedagogy. School to supply concrete lesson examples for further detail.'},
 {type:'cards',title:'A broader school experience',items:[['Sports & wellbeing','Movement, play, yoga and the proposed sports programme.','sports'],['School life','Clubs, cultural activities, life skills and shared experiences.','school-life']],note:'Principal: Sports, Activities and Life @SDKS-SSA.'},
 {type:'faq',title:'Learning information',items:[['Languages and curriculum','[Approved language policy and curriculum description.]'],['Understanding each child’s progress','[School’s assessment and parent communication approach.]'],['Future classes','[Approved expansion plan, clearly distinguished from classes currently offered.]']],note:'Discovery: academic structure and expansion plan. Do not publish a promised Class XII timeline from an unresolved planning entry.'}]},
 'early-years':{title:'Nursery–Class II',group:'Learning',intro:'A thoughtful beginning to school.',desc:'Play-based learning with early literacy, numeracy, creativity and social-emotional development.',image:'Early-years learning environment',note:'Principal: Foundation Stage, described as Pre-Nursery–II. Discovery/user: Nursery–V launch. Confirm entry class.',sections:[
 {type:'cards',title:'Foundations for learning',items:[['Language & expression','Listening, speaking, stories and early reading.'],['Numbers & discovery','Early numeracy through age-appropriate exploration.'],['Creativity & social skills','Making, playing and learning with others.']],note:'Principal: Foundation Stage. Illustrative activity labels, subject to academic review.'},
 {type:'split',title:'Space to explore',text:'[Describe the approved early-years classroom setting and how activities will support children’s learning.]',image:'Classroom / play-based activity',note:'Principal: caring, joyful, play-based learning. No assumptions about class size or facilities.'},
 {type:'faq',title:'Care and everyday routines',items:[['Settling into school','[School-approved settling-in arrangements.]'],['Adult support and supervision','[Verified arrangements for younger children.]'],['Communication with families','[Confirmed communication channels and routine.]']],note:'Proposed practical information slots, not confirmed services. Retain only after school confirmation.'},
 {type:'cta',title:'Explore admission information',link:'admissions',label:'Admissions',secondary:'primary',secondaryLabel:'See Classes III–V'}]},
 primary:{title:'Classes III–V',group:'Learning',intro:'Growing understanding and independence.',desc:'Experiential and inquiry-based learning across languages, mathematics, science, social understanding and creative expression.',image:'Primary classroom / enquiry activity',note:'Principal: Preparatory Stage, Classes III–V.',sections:[
 {type:'cards',title:'Areas of learning',items:[['Languages','Reading, expression and communication.'],['Mathematics & science','Reasoning, discovery and understanding.'],['Social understanding & creativity','Exploring ideas, people and creative possibilities.']],note:'Principal: Preparatory Stage. Detailed subjects, languages and curriculum wording require school approval.'},
 {type:'split',title:'Questions become exploration',text:'[One school-supplied example of an inquiry or project, showing how children investigate and explain what they learn.]',image:'Project / classroom work example',reverse:true,note:'Principal: inquiry-based teaching. Placeholder avoids fabricating actual student work.'},
 {type:'faq',title:'Progress and support',items:[['Learning progress','[Approved approach to assessment and feedback.]'],['Support for different learning needs','[Confirmed academic support arrangements.]'],['Progression after Class V','[School-approved future plan; do not imply higher classes are currently available.]']],note:'Discovery: academic approach and future expansion. Support details remain open.'},
 {type:'cta',title:'Learning beyond lessons',link:'school-life',label:'Explore school life',secondary:'admissions',secondaryLabel:'Admissions'}]},
 campus:{title:'Campus & Facilities',group:'Campus',intro:'Our campus in Patiala',desc:'The campus is under development. Planned facilities include smart classrooms, a multipurpose hall, activity rooms and a wellness and yoga centre.',image:'Campus overview / approved architectural render',note:'Discovery: under construction; principal: infrastructure. Current progress and facility readiness require an update.',sections:[
 {type:'cards',title:'Learning spaces',items:[['Smart classrooms','[Approved description and readiness.]'],['Multipurpose hall','[Planned use and readiness.]'],['Activity rooms','[Approved activities and readiness.]'],['Wellness & yoga centre','[Approved provision and readiness.]']],note:'All four spaces are named in the principal’s draft. Do not add labs/robotics/library as confirmed facilities merely because discovery requests information about them.'},
 {type:'split',title:'Campus progress',text:'[Latest dated update describing what is complete, what is being developed and the next confirmed milestone.]',image:'Dated site-progress photograph',link:'gallery',label:'View gallery & progress',reverse:true,note:'Discovery: construction status and media requested. No invented completion percentages.'},
 {type:'faq',title:'Practical campus information',items:[['Safety and supervision','[Verified access, supervision and emergency arrangements.]'],['Accessibility and care','[Confirmed accessibility and wellbeing facilities.]'],['Getting to school','[Confirmed location, visitor entry and transport availability.]']],note:'Discovery: safety, medical and transport details requested. These are information slots, not promises.'},
 {type:'cta',title:'Find the school',link:'contact',label:'Location & contact',secondary:'sports',secondaryLabel:'Sports & wellbeing'}]},
 sports:{title:'Sports & Wellbeing',group:'Learning',intro:'Sports, yoga and meditation',desc:'Plans include athletics, cricket, basketball, table tennis, badminton and archery, alongside yoga and meditation.',image:'Sports / movement image',note:'Principal: Sports. Age suitability, coaching, launch readiness and facilities must be confirmed.',sections:[
 {type:'list',title:'Proposed sports programme',items:[['Athletics','Track specification and availability to confirm.'],['Cricket & basketball','Facilities, age groups and programme to confirm.'],['Table tennis & badminton','Programme and facilities to confirm.'],['Archery','Age suitability, supervision and availability to confirm.']],note:'Principal lists all six sports, including a 400m track. No completed-track claim until verified.'},
 {type:'split',title:'Yoga and meditation',text:'[School-approved explanation of age-appropriate yoga and meditation, including how it fits into the school routine.]',image:'Wellness space / age-appropriate session',note:'Principal: Yoga & Meditation Centre; assembly and meditation.'},
 {type:'cta',title:'Explore the spaces behind the programme',link:'campus',label:'Campus & facilities'}]},
 'school-life':{title:'School Life',group:'Learning',intro:'Life at SDKS',desc:'Plans for school life include houses, clubs, cultural activities and festivals, life skills, assemblies and meditation.',image:'Creative / collaborative activity image',note:'Principal: Activities and Life @SDKS-SSA. Proposed experiences, not evidence of existing enrolment.',sections:[
 {type:'cards',title:'Beyond the classroom',items:[['House system & clubs','[Approved structure, purpose and opportunities.]'],['Cultural activities & festivals','[Examples of planned cultural participation.]'],['Life skills','[Concrete school-supplied examples.]']],note:'Principal: Activities. No invented club names or event calendar.'},
 {type:'split',title:'Assemblies and meditation',text:'Assemblies and meditation form part of the school’s plans for a value-based learning environment.',image:'Assembly / group activity image',reverse:true,note:'Principal: Assembly & Meditation; value-based learning environment. Frequency and examples awaited.'},
 {type:'cta',title:'Explore another part of school life',link:'sports',label:'Sports & wellbeing',secondary:'gallery',secondaryLabel:'Gallery'}]},
 admissions:{title:'Admissions',group:'Practical',intro:'Admission information',desc:'The first-year class range is Nursery to Class V. Details of the admission process, eligibility and fees will be added once confirmed by the school.',image:null,note:'Discovery/user: Nursery–V; dates/process/fees not provided. Permanent Admissions page.',sections:[
 {type:'notice',title:'Admission status',text:'Admissions have not opened yet. Contact the school for information.',note:'Latest user confirmation. Do not invent an opening date, active applications or seat availability.'},
 {type:'cards',title:'Classes',items:[['Nursery–Class II','Explore the foundational learning approach.','early-years'],['Classes III–V','Explore the preparatory learning approach.','primary']],note:'Discovery: Year 1 Nursery–V. Exact entry stages and eligibility need confirmation.'},
 {type:'steps',title:'Admission process',items:[['Speak with the school','[Confirmed enquiry channel and contact.]'],['Review requirements','[Approved eligibility, dates and required documents.]'],['Complete the next steps','[School-approved application and confirmation process.]']],note:'Principal requests admission process; these are proposed placeholder stages, not an approved admissions policy.'},
 {type:'docs',title:'Admission resources',items:['Prospectus','School uniform guidelines','Scholarship information'],note:'Principal: Admission. Files and scholarship applicability not yet supplied.'},
 {type:'faq',title:'Practical information',items:[['Eligibility and academic session','[Confirmed class eligibility, age criteria and session dates.]'],['Fees and inclusions','[Class-wise fees, inclusions and additional charges.]'],['Transport','[Availability, routes and transport charges, if offered.]']],note:'Discovery: dates, fees, eligibility and transport requested.'},
 {type:'cta',title:'Fees and school information',link:'fees',label:'View fee information'},
 {type:'form',title:'Admission enquiry',note:'Principal: Admission Inquiry Form. Demo only; no personal information is collected or sent.'}]},
 fees:{title:'Fees & Information',group:'Practical',intro:'Fees and school information',desc:'Fee details are awaiting confirmation from the school.',image:null,note:'Discovery: fee structure requested; CBSE disclosure planning includes fees. No amounts supplied.',sections:[
 {type:'table',title:'Fee structure',headers:['Class / stage','Fee components','Payment schedule'],rows:[['Nursery–Class II','To be supplied','To be supplied'],['Classes III–V','To be supplied','To be supplied']],note:'No invented fees. Keep one approved fee source shared with Admissions and Disclosure.'},
 {type:'faq',title:'What families need to know',items:[['What is included','[Approved inclusions and additional charges.]'],['Uniform and learning materials','[Approved purchasing and uniform information.]'],['Scholarships','[Eligibility and terms only if the school confirms a scholarship programme.]']],note:'Principal: uniform and scholarship information. Discovery: approved public fees.'},
 {type:'docs',title:'Downloads',items:['Approved fee schedule','Uniform guidelines'],note:'Download positions only. No dummy documents.'},
 {type:'cta',title:'Need clarification?',link:'contact',label:'Contact the school'}]},
 gallery:{title:'Gallery & Campus Progress',group:'Campus',intro:'Campus photographs and progress',desc:'[Dated campus photographs and architectural views with captions.]',image:null,note:'Principal homepage reference: gallery. Discovery: current visuals, plans and renders. Can remain within Campus if assets are limited.',sections:[
 {type:'gallery',title:'Campus views',items:['Campus overview','Learning spaces','Outdoor spaces','Dated construction progress','Proposed architectural view','Facilities detail'],note:'Each item is an image slot. Actual vs proposed status, date, caption and rights must be checked.'},
 {type:'cta',title:'Read about the campus',link:'campus',label:'Campus & facilities'}]},
 updates:{title:'School Updates',group:'School',intro:'School updates',desc:'[School announcements and campus updates, with publication dates.]',image:null,note:'Principal homepage reference: Latest News & Updates. Hide from live navigation until real notices exist.',sections:[
 {type:'list',title:'Latest updates',items:[['School announcement','[Approved title, publication date and summary.]'],['Campus update','[Dated progress summary and photograph.]'],['Admission notice','[Confirmed dates and official information when available.]']],note:'These are notice slots, not events that have happened.'},
 {type:'cta',title:'Have a question?',link:'contact',label:'Contact the school'}]},
 contact:{title:'Contact the School',group:'Practical',intro:'Contact SDKS Sri Sri Academy',desc:'For questions about the school or admissions, use the contact details or enquiry form below.',image:null,note:'Principal: Contact and top strip. Official contacts and enquiry owner requested. Visitor address must be checked separately from approved invoice address.',sections:[
 {type:'contact',title:'Contact & location',note:'Official phone, email, office hours and visitor location require verification. Do not use private contact details or assume the invoice address is the visitor entrance.'},
 {type:'form',title:'Send an enquiry',note:'Demo only. No submission, storage, analytics or external form integration.'}]},
 careers:{title:'Careers',group:'School',intro:'Careers at SDKS',desc:'[Confirmed teaching and administrative vacancies and application details.]',image:null,note:'Principal: Careers. No vacancy is being advertised by this prototype.',sections:[
 {type:'list',title:'Opportunities',items:[['Teaching roles','[Confirmed vacancy, qualifications and application deadline.]'],['Administrative roles','[Confirmed vacancy, experience and application deadline.]']],note:'Placeholder listings only. Publish genuine approved openings.'},
 {type:'prose',title:'How to apply',text:'[Approved application instructions, official recruitment contact and required information.]',note:'Principal requests an application form/process. Confirm collection, recipient and privacy handling before adding upload functionality.'},
 {type:'cta',title:'About the school',link:'about',label:'Our people and purpose'}]},
 disclosure:{title:'Mandatory Public Disclosure',group:'School',intro:'School information and documents.',desc:'An organised place for official information and applicable school documents.',image:null,note:'Disclosure planning from the existing website requirements and CBSE Appendix IX reference. School must verify applicability and approve every entry.',sections:[
 {type:'table',title:'General information',headers:['Information','Details'],rows:[['School name','SDKS Sri Sri Academy, Patiala'],['Affiliation / school code','To be verified'],['Address & contact','Approved details to be supplied'],['Principal & qualification','To be supplied']],note:'Principal draft says “To be affiliated to CBSE.” No affiliation number or status invented.'},
 {type:'docs',title:'Documents & certificates',items:['Affiliation / recognition documents, as applicable','Society / trust registration','NOC, as applicable','Building and fire safety certificates','DEO / self-certification, as applicable','Water, health and sanitation documents'],note:'Document groups are placeholders, not confirmation that certificates exist.'},
 {type:'docs',title:'Academic information',items:['Fee structure','Academic calendar','School management committee','Parent teacher association, as applicable','Board results, as applicable'],note:'Use the applicable official disclosure format. Never fabricate historic results for a new school.'},
 {type:'table',title:'Staff & infrastructure',headers:['Category','Information placement'],rows:[['Staff','Approved names, qualifications and applicable staffing details'],['Infrastructure','Verified areas, classrooms, laboratories, library and facilities'],['Inspection','Applicable inspection video / official link']],note:'Expanded values and document links to be completed by the school.'}]},
 privacy:{title:'Privacy',group:'School',intro:'Privacy notice',desc:'[School-approved privacy notice for enquiry and application information.]',image:null,note:'This is a policy wireframe, not a completed legal policy.',sections:[
 {type:'prose',title:'Information and purpose',text:'[Explain what the implemented enquiry or application forms collect and why.]'},
 {type:'prose',title:'Storage, sharing and retention',text:'[Describe the actual school-approved practices and relevant service providers.]'},
 {type:'prose',title:'Your questions and choices',text:'[Provide the official privacy contact and applicable choices.]'},
 {type:'prose',title:'Website services and updates',text:'[Describe cookies/analytics only as implemented and show the notice revision date.]',note:'This prototype does not collect form data or use analytics.'}]}
};
