/* Website review content only. No personal records or source attachments. */
const pages = {
 home:{title:'Home',group:'Start',intro:'A school for learning, growing and belonging.',desc:'SDKS Sri Sri Academy, Patiala. A child-centred approach to learning, from Nursery to Class V.',image:'School introduction / welcoming campus image',note:'Principal: About, Vision & Mission. Discovery: Year 1 Nursery–V. Use a genuine approved photograph or clearly labelled campus render.',sections:[
 {type:'split',title:'An education rooted in values',text:'The school’s proposed approach brings together contemporary learning, experiential education and the values described in the principal’s draft.',image:'Principal / people behind the school',link:'about',label:'Meet the school',note:'Principal: About. Discovery: management and principal profiles requested. Profiles and institutional wording need approval.'},
 {type:'cards',title:'Learning at every stage',items:[['Nursery–Class II','Play, early language, numbers and creative expression.','early-years'],['Classes III–V','Inquiry, understanding and increasingly independent learning.','primary']],note:'Principal: Foundation and Preparatory stages. Nursery entry follows discovery/user; Pre-Nursery in principal draft needs reconciliation.'},
 {type:'split',title:'Beyond the classroom',text:'Space for sport, creative activities, cultural experiences and everyday life skills.',image:'Age-appropriate activity image',link:'school-life',label:'Explore school life',reverse:true,note:'Principal: Activities, Sports and Life @SDKS-SSA. This is proposed provision, not evidence of existing student life.'},
 {type:'split',title:'Discover the campus',text:'Explore the planned learning spaces and follow the development of the school campus.',image:'Campus overview / dated progress photograph',link:'campus',label:'Explore the campus',note:'Discovery: campus under construction. Principal: infrastructure list. Clearly distinguish real progress photographs from proposed renders.'},
 {type:'cta',title:'Get to know SDKS',text:'Find admission information or speak with the school.',link:'admissions',label:'Admission information',secondary:'contact',secondaryLabel:'Contact the school'}]},
 about:{title:'About the School',group:'About',intro:'The people and purpose behind SDKS.',desc:'The principal’s draft brings together the values of Sanatan Dharma Kumar Sabha and an educational philosophy inspired by Gurudev Sri Sri Ravi Shankar.',image:'School / institutional photograph',note:'Principal: About. Exact legal association wording and asset permissions require approval.',sections:[
 {type:'prose',title:'Our story',text:'SDKS Sri Sri Academy is being developed in Patiala with an emphasis on responsible, compassionate and value-driven learning. This section introduces the school’s origins and the role of the organisations behind it.',note:'Principal: About; Discovery: School Overview. Refine and approve the institutional story before publication.'},
 {type:'cards',title:'Our vision and mission',items:[['Vision','To nurture confident, compassionate and capable individuals through holistic, value-based education.'],['Mission','Child-centred, experiential and joyful learning that respects each learner’s individuality and pace.']],note:'Condensed from the principal’s Vision and Mission; no invented quotation.'},
 {type:'split',title:'A message from the principal',text:'[Approved message introducing the educational approach and the principal’s priorities for children.]',image:'Principal portrait',note:'Discovery: principal profile, photograph and message requested. Do not invent a name, qualification or message.'},
 {type:'cards',title:'School leadership',items:[['Management','[Name, role, brief introduction and approved portrait.]'],['Academic leadership','[Name, role and relevant experience.]']],note:'Discovery: founder/management and academic-head details. Keep within About unless enough material supports a separate page.'},
 {type:'cta',title:'See how the approach becomes learning',link:'learning',label:'Explore learning'}]},
 learning:{title:'Learning',group:'Learning',intro:'Learning that involves the whole child.',desc:'The principal proposes a combination of academic foundations, experiential learning and emotional, physical and social development.',image:'Learning / teacher interaction image',note:'Principal: About, Mission and Pedagogy.',sections:[
 {type:'cards',title:'Choose a learning stage',items:[['Nursery–Class II','A play-based foundation in language, numbers, creativity and social skills.','early-years'],['Classes III–V','An inquiry-based approach to subjects, ideas and everyday understanding.','primary']],note:'Principal stages; discovery confirms Year 1 Nursery–Class V.'},
 {type:'split',title:'Learning through experience',text:'Room for exploration, conversation and hands-on activity. The detailed examples here will show how the school plans to put this approach into practice.',image:'Hands-on activity / learning materials',note:'Principal: experiential and inquiry-based teaching. Actual lesson examples must come from the school.'},
 {type:'cards',title:'A broader school experience',items:[['Sports & wellbeing','Movement, play, yoga and the proposed sports programme.','sports'],['School life','Clubs, cultural activities, life skills and shared experiences.','school-life']],note:'Principal: Sports, Activities and Life @SDKS-SSA.'},
 {type:'faq',title:'Learning information',items:[['Languages and curriculum','[Approved language policy and curriculum description.]'],['Understanding each child’s progress','[School’s assessment and parent communication approach.]'],['Future classes','[Approved expansion plan, clearly distinguished from classes currently offered.]']],note:'Discovery: academic structure and expansion plan. Do not publish a promised Class XII timeline from an unresolved planning entry.'}]},
 'early-years':{title:'Nursery–Class II',group:'Learning',intro:'A thoughtful beginning to school.',desc:'Play-based learning with early literacy, numeracy, creativity and social-emotional development.',image:'Early-years learning environment',note:'Principal: Foundation Stage, described as Pre-Nursery–II. Discovery/user: Nursery–V launch. Confirm entry class.',sections:[
 {type:'cards',title:'Foundations for learning',items:[['Language & expression','Listening, speaking, stories and early reading.'],['Numbers & discovery','Early numeracy through age-appropriate exploration.'],['Creativity & social skills','Making, playing and learning with others.']],note:'Principal: Foundation Stage. Illustrative activity labels, subject to academic review.'},
 {type:'split',title:'Space to explore',text:'[Describe the approved early-years classroom setting and how activities will support children’s learning.]',image:'Classroom / play-based activity',note:'Principal: caring, joyful, play-based learning. No assumptions about class size or facilities.'},
 {type:'faq',title:'Care and everyday routines',items:[['Settling into school','[School-approved settling-in arrangements.]'],['Adult support and supervision','[Verified arrangements for younger children.]'],['Communication with families','[Confirmed communication channels and routine.]']],note:'Proposed practical information slots, not confirmed services. Retain only after school confirmation.'},
 {type:'cta',title:'Explore admission information',link:'admissions',label:'Admissions',secondary:'primary',secondaryLabel:'See Classes III–V'}]},
 primary:{title:'Classes III–V',group:'Learning',intro:'Growing understanding and independence.',desc:'Experiential and inquiry-based learning across languages, mathematics, science, social understanding and creative expression.',image:'Primary classroom / enquiry activity',note:'Principal: Preparatory Stage, Classes III–V.',sections:[
 {type:'cards',title:'Areas of learning',items:[['Languages','Reading, expression and communication.'],['Mathematics & science','Reasoning, discovery and understanding.'],['Social understanding & creativity','Exploring ideas, people and creative possibilities.']],note:'Principal: Preparatory Stage. Detailed subjects, languages and curriculum wording require school approval.'},
 {type:'split',title:'Questions become exploration',text:'[One school-supplied example of an inquiry or project, showing how children investigate and explain what they learn.]',image:'Project / classroom work example',reverse:true,note:'Principal: inquiry-based teaching. Placeholder avoids fabricating actual student work.'},
 {type:'faq',title:'Progress and support',items:[['Learning progress','[Approved approach to assessment and feedback.]'],['Support for different learning needs','[Confirmed academic support arrangements.]'],['Progression after Class V','[School-approved future plan; do not imply higher classes are currently available.]']],note:'Discovery: academic approach and future expansion. Support details remain open.'},
 {type:'cta',title:'Learning beyond lessons',link:'school-life',label:'Explore school life',secondary:'admissions',secondaryLabel:'Admissions'}]},
 campus:{title:'Campus & Facilities',group:'Campus',intro:'Spaces for learning and discovery.',desc:'Explore the school’s proposed facilities and the development of its Patiala campus.',image:'Campus overview / approved architectural render',note:'Discovery: under construction; principal: infrastructure. All readiness and visual labels require confirmation.',sections:[
 {type:'cards',title:'Learning spaces',items:[['Smart classrooms','[Approved description and readiness.]'],['Multipurpose hall','[Planned use and readiness.]'],['Activity rooms','[Approved activities and readiness.]'],['Wellness & yoga centre','[Approved provision and readiness.]']],note:'All four spaces are named in the principal’s draft. Do not add labs/robotics/library as confirmed facilities merely because discovery requests information about them.'},
 {type:'split',title:'Campus progress',text:'[Latest dated update describing what is complete, what is being developed and the next confirmed milestone.]',image:'Dated site-progress photograph',link:'gallery',label:'View gallery & progress',reverse:true,note:'Discovery: construction status and media requested. No invented completion percentages.'},
 {type:'faq',title:'Practical campus information',items:[['Safety and supervision','[Verified access, supervision and emergency arrangements.]'],['Accessibility and care','[Confirmed accessibility and wellbeing facilities.]'],['Getting to school','[Confirmed location, visitor entry and transport availability.]']],note:'Discovery: safety, medical and transport details requested. These are information slots, not promises.'},
 {type:'cta',title:'Find the school',link:'contact',label:'Location & contact',secondary:'sports',secondaryLabel:'Sports & wellbeing'}]},
 sports:{title:'Sports & Wellbeing',group:'Learning',intro:'Movement as part of learning.',desc:'The principal’s draft includes sport, yoga and meditation within the proposed school experience.',image:'Sports / movement image',note:'Principal: Sports. Age suitability, coaching, launch readiness and facilities must be confirmed.',sections:[
 {type:'list',title:'Proposed sports programme',items:[['Athletics','Track specification and availability to confirm.'],['Cricket & basketball','Facilities, age groups and programme to confirm.'],['Table tennis & badminton','Programme and facilities to confirm.'],['Archery','Age suitability, supervision and availability to confirm.']],note:'Principal lists all six sports, including a 400m track. No completed-track claim until verified.'},
 {type:'split',title:'Yoga and meditation',text:'[School-approved explanation of age-appropriate yoga and meditation, including how it fits into the school routine.]',image:'Wellness space / age-appropriate session',note:'Principal: Yoga & Meditation Centre; assembly and meditation.'},
 {type:'cta',title:'Explore the spaces behind the programme',link:'campus',label:'Campus & facilities'}]},
 'school-life':{title:'School Life',group:'Learning',intro:'More ways to participate and grow.',desc:'Cultural experiences, clubs and life skills form part of the proposed learning environment.',image:'Creative / collaborative activity image',note:'Principal: Activities and Life @SDKS-SSA. Proposed experiences, not evidence of existing enrolment.',sections:[
 {type:'cards',title:'Beyond the classroom',items:[['House system & clubs','[Approved structure, purpose and opportunities.]'],['Cultural activities & festivals','[Examples of planned cultural participation.]'],['Life skills','[Concrete school-supplied examples.]']],note:'Principal: Activities. No invented club names or event calendar.'},
 {type:'split',title:'Shared moments, everyday values',text:'Assemblies and meditation are included in the principal’s draft. This section explains their intended role in everyday school life.',image:'Assembly / group activity image',reverse:true,note:'Principal: Assembly & Meditation; value-based learning environment.'},
 {type:'cta',title:'Explore another part of school life',link:'sports',label:'Sports & wellbeing',secondary:'gallery',secondaryLabel:'Gallery'}]},
 admissions:{title:'Admissions',group:'Practical',intro:'Your next step with SDKS.',desc:'Explore the class structure, admission information and the documents families will need.',image:null,note:'Permanent Admissions page. Status/dates are editable content, not a separate pre-admission website.',sections:[
 {type:'notice',title:'Admission status',text:'Admissions have not opened yet. Contact the school for information.',note:'Latest user confirmation. Do not invent an opening date, active applications or seat availability.'},
 {type:'cards',title:'Classes',items:[['Nursery–Class II','Explore the foundational learning approach.','early-years'],['Classes III–V','Explore the preparatory learning approach.','primary']],note:'Discovery: Year 1 Nursery–V. Exact entry stages and eligibility need confirmation.'},
 {type:'steps',title:'Admission process',items:[['Speak with the school','[Confirmed enquiry channel and contact.]'],['Review requirements','[Approved eligibility, dates and required documents.]'],['Complete the next steps','[School-approved application and confirmation process.]']],note:'Principal requests admission process; these are proposed placeholder stages, not an approved admissions policy.'},
 {type:'docs',title:'Admission resources',items:['Prospectus','School uniform guidelines','Scholarship information'],note:'Principal: Admission. Files and scholarship applicability not yet supplied.'},
 {type:'faq',title:'Practical information',items:[['Eligibility and academic session','[Confirmed class eligibility, age criteria and session dates.]'],['Fees and inclusions','See the Fees & Information page for the proposed information structure.'],['Transport','[Publish availability and routes only when confirmed.]']],note:'Discovery: dates, fees, eligibility and transport requested.'},
 {type:'cta',title:'Fees and school information',link:'fees',label:'View fee information'},
 {type:'form',title:'Admission enquiry',note:'Principal: Admission Inquiry Form. Demo only; no personal information is collected or sent.'}]},
 fees:{title:'Fees & Information',group:'Practical',intro:'Clear information for families.',desc:'A dedicated place for approved fees, inclusions and practical admission details.',image:null,note:'Discovery: fee structure requested; CBSE disclosure planning includes fees. No amounts supplied.',sections:[
 {type:'table',title:'Fee structure',headers:['Class / stage','Fee components','Payment schedule'],rows:[['Nursery–Class II','To be supplied','To be supplied'],['Classes III–V','To be supplied','To be supplied']],note:'No invented fees. Keep one approved fee source shared with Admissions and Disclosure.'},
 {type:'faq',title:'What families need to know',items:[['What is included','[Approved inclusions and additional charges.]'],['Uniform and learning materials','[Approved purchasing and uniform information.]'],['Scholarships','[Eligibility and terms only if the school confirms a scholarship programme.]']],note:'Principal: uniform and scholarship information. Discovery: approved public fees.'},
 {type:'docs',title:'Downloads',items:['Approved fee schedule','Uniform guidelines'],note:'Download positions only. No dummy documents.'},
 {type:'cta',title:'Need clarification?',link:'contact',label:'Contact the school'}]},
 gallery:{title:'Gallery & Campus Progress',group:'Campus',intro:'A closer look at the school.',desc:'A place for approved campus photographs, progress updates and clearly labelled architectural views.',image:null,note:'Principal homepage reference: gallery. Discovery: current visuals, plans and renders. Can remain within Campus if assets are limited.',sections:[
 {type:'gallery',title:'Campus views',items:['Campus overview','Learning spaces','Outdoor spaces','Dated construction progress','Proposed architectural view','Facilities detail'],note:'Each item is an image slot. Actual vs proposed status, date, caption and rights must be checked.'},
 {type:'cta',title:'Read about the campus',link:'campus',label:'Campus & facilities'}]},
 updates:{title:'School Updates',group:'School',intro:'News and information from SDKS.',desc:'A place for confirmed school announcements and campus updates.',image:null,note:'Principal homepage reference: Latest News & Updates. Hide from live navigation until real notices exist.',sections:[
 {type:'list',title:'Latest updates',items:[['School announcement','[Approved title, publication date and summary.]'],['Campus update','[Dated progress summary and photograph.]'],['Admission notice','[Confirmed dates and official information when available.]']],note:'These are notice slots, not events that have happened.'},
 {type:'cta',title:'Have a question?',link:'contact',label:'Contact the school'}]},
 contact:{title:'Contact the School',group:'Practical',intro:'Let’s talk about your child’s school journey.',desc:'Speak with the school or find the information you need before a visit.',image:null,note:'Principal: Contact and top strip. Discovery: exact campus address, Maps, official contacts and enquiry owner requested.',sections:[
 {type:'contact',title:'Contact & location',note:'Official phone, email, office hours and visitor location require verification. Do not use private contact details or assume the invoice address is the visitor entrance.'},
 {type:'form',title:'Send an enquiry',note:'Demo only. No submission, storage, analytics or external form integration.'}]},
 careers:{title:'Careers',group:'School',intro:'Work with the school.',desc:'A place for teaching and administrative opportunities at SDKS Sri Sri Academy.',image:null,note:'Principal: Careers. No vacancy is being advertised by this prototype.',sections:[
 {type:'list',title:'Opportunities',items:[['Teaching roles','[Confirmed vacancy, qualifications and application deadline.]'],['Administrative roles','[Confirmed vacancy, experience and application deadline.]']],note:'Placeholder listings only. Publish genuine approved openings.'},
 {type:'prose',title:'How to apply',text:'[Approved application instructions, official recruitment contact and required information.]',note:'Principal requests an application form/process. Confirm collection, recipient and privacy handling before adding upload functionality.'},
 {type:'cta',title:'About the school',link:'about',label:'Our people and purpose'}]},
 disclosure:{title:'Mandatory Public Disclosure',group:'School',intro:'School information and documents.',desc:'An organised place for official information and applicable school documents.',image:null,note:'Disclosure planning from the existing website requirements and CBSE Appendix IX reference. School must verify applicability and approve every entry.',sections:[
 {type:'table',title:'General information',headers:['Information','Details'],rows:[['School name','SDKS Sri Sri Academy, Patiala'],['Affiliation / school code','To be verified'],['Address & contact','Approved details to be supplied'],['Principal & qualification','To be supplied']],note:'Principal draft says “To be affiliated to CBSE.” No affiliation number or status invented.'},
 {type:'docs',title:'Documents & certificates',items:['Affiliation / recognition documents, as applicable','Society / trust registration','NOC, as applicable','Building and fire safety certificates','DEO / self-certification, as applicable','Water, health and sanitation documents'],note:'Document groups are placeholders, not confirmation that certificates exist.'},
 {type:'docs',title:'Academic information',items:['Fee structure','Academic calendar','School management committee','Parent teacher association, as applicable','Board results, as applicable'],note:'Use the applicable official disclosure format. Never fabricate historic results for a new school.'},
 {type:'table',title:'Staff & infrastructure',headers:['Category','Information placement'],rows:[['Staff','Approved names, qualifications and applicable staffing details'],['Infrastructure','Verified areas, classrooms, laboratories, library and facilities'],['Inspection','Applicable inspection video / official link']],note:'Expanded values and document links to be completed by the school.'}]},
 privacy:{title:'Privacy',group:'School',intro:'How information will be handled.',desc:'Placement for the school-approved privacy notice.',image:null,note:'This is a policy wireframe, not a completed legal policy.',sections:[
 {type:'prose',title:'Information and purpose',text:'[Explain what the implemented enquiry or application forms collect and why.]'},
 {type:'prose',title:'Storage, sharing and retention',text:'[Describe the actual school-approved practices and relevant service providers.]'},
 {type:'prose',title:'Your questions and choices',text:'[Provide the official privacy contact and applicable choices.]'},
 {type:'prose',title:'Website services and updates',text:'[Describe cookies/analytics only as implemented and show the notice revision date.]',note:'This prototype does not collect form data or use analytics.'}]}
};
